added user's profile with tests
katlasik/auctions-kb pull request #14
Opened 2020-10-18 12:43 UTC by Lukareus

added user's profile with tests

2020-10-18 12:55 UTC, KasiaMajchrzak approved these changes

2020-10-18 19:03 UTC, katlasik commented on pom.xml
> +            <version>8.0.16</version>
Domyślnie maven bieże wersję connectora z spring-boot-starter-parent i nie trzeba jej jawnie podawać.Miałeś jakiś problem z zależnościami, ze to dodałeś jawnie?

2020-10-18 19:04 UTC, katlasik commented on src/test/java/pl/sda/auctions/controllers/HomeControllerTest.java
> +        User user = new pl.sda.auctions.model.User(2L, "name@gmail.com", "pass123", "Username", true, Role.USER);
Nie musisz używać jawnie podanej ścieżki: pl.sda.auctions.model.User tylko samo User.

2020-10-18 19:04 UTC, katlasik requested changes
Dwa małe szczegóły:
* wyrzuć version z maven (chyba, że z jakiegoś powodu potrzebujesz)
* zmień pl.sda.auctions.model.User na User w teście

2020-10-18 19:13 UTC, katlasik approved these changes
Jak zrobisz poprawki to możesz mergować.

2020-10-20 06:55 UTC, KasiaMajchrzak approved these changes

2020-10-25 08:41 UTC, merged